### ISSUE TITLE
Super unofficial windows build if anyone needs it

### ISSUE THREAD

**Issue by willy-vvu** [lachs0r/cadmousectl#6]
Compiled with hidapi, should be good to go.
[cadmousectl.zip](https://github.com/lachs0r/cadmousectl/files/2660035/cadmousectl.zip)

-Willy

**Comment by willy-vvu** [comment]
3Dxware feels like massive bloatware compared to this script - thanks so much for developing this!

**Comment by lachs0r** [comment]
I have digitally signed Windows builds here now: http://repos.cirno.systems:82/mingw-w64:/publish/cadmousectl/

Can you test whether these work? I will put them on the GitHub release page then.

**Comment by lachs0r** [comment]
Thanks for testing.
